from pptx import Presentation

def create_ppt(text):

    prs = Presentation()

    # Slide 1: Title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "AI Data Analysis Report"
    slide.placeholders[1].text = "Generated by AI Data Analyst Agent"

    # Split insight into lines
    lines = text.split("\n")

    # Slide 2: Insights
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Key Insights"

    content = "\n".join(lines[:5])
    slide.placeholders[1].text = content

    # Slide 3: Additional Analysis
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Detailed Analysis"

    content2 = "\n".join(lines[5:10])
    slide.placeholders[1].text = content2

    # Slide 4: Conclusion
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Conclusion"

    slide.placeholders[1].text = lines[-1] if len(lines) > 0 else "Summary of the dataset."

    file = "AI_Report.pptx"

    prs.save(file)

    return file
